name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  create_pdf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: mrtj/actions-makepdfs@master
        if: github.ref == 'refs/heads/master'
      - uses: actions/upload-artifact@v1
        with:
          markdown_dir: documents
          name: platform-architecture-docs
          path: tmp
